import CARDA from './CARDA.png'
import Polycat1 from './Polycat1.png'
import Polycat2 from './Polycat2.png'
import Polycat3 from './Polycat3.png'
import LYGON from './LYGON.png'
import ETHE from './ETHE.png'
import ANCE from './ANCE.png'
import BITIC from './BITIC.png'
import ancee from './ancee.png'
import biticc from './biticc.png'
import ethee from './ethee.png'

export const data = [

    {bg:"linear-gradient(to right, #c6ffdd, #fbd786, #f7797d)",img:BITIC,name:"Bitic",desc:"Coming from the Lightning network. Legendary type of PolyMon.", details:"Bitic, the thunder dragon Polymon, holds domain over a large area of land. The land is mostly mountainous, and few other Polymon and humans live there. This is just as Bitic wants, as it prefers its own solitude. Bitic gathers enormous amounts of energy inside it simply by existing. Often, this energy needs to be released. Bitic releases it by creating large thunder and lightning explosions with it at the center. Those explosions do not harm Bitic, but make craters out of the nearby land. This is why Bitic prefers solitude, as anything near the explosion faces an early death.", rank:"01", isSale:true,main: false},
    {bg:"linear-gradient(to right, #ff9966, #ff5e62)",img:ETHE,name:"Ethe",desc:"Defender of Ether. Legendary type of PolyMon.", details:"Ethe, the legendary star steel dragon Polymon, is always roaming the world looking for powerful adversaries. Like Lygon, Ethe lives high up in the sky, beyond the atmosphere. Also like Lygon, it often comes descends. However, where Lygon comes down into the world to give gifts on specific days, Ethe only appears to affirm its supremacy. From high up beyond the atmosphere, Ethe is still able to see what is going on in the world. The moment it sees another Polymon boast of its strength, Ethe descends and challenges the other Polymon to a fight.",rbtn:"DARK",rbg:"#333",rank:"02", isSale:false,main: false},
    {bg:"linear-gradient(to right, #1e9600, #fff200, #ff0000)",img:CARDA,name:"Carda",desc:"An uncommon Polymon in the Polyverse.", details:"Carda is a legendary Polymon. It lives in the bottom of the deepest seas, and, as such, not many people have seen it. Carda acts as a protector of the deep seas, keeping watch both for human intrusions and also for other Polymon wishing to enter the area. If the need arises, Carda is more than capable of defending its territory and the Polymon it considers to be its wards.Carda’s more terrifying feature is its roar. Akin to a lion’s roar but magnified tenfold, it is often enough to cause other Polymon to flee without a fight.",rbtn:"WATER",rbg:"#0034af",rank:"03", isSale:false,main: false},
    {bg:"linear-gradient(to right, #0099f7, #f11712)",img:LYGON,name:"Lygon",desc:"Lygon created by BSC. A man bred PolyMon.", details:"Lygon is the legendary celestial Polygon. Although it lives high up in the sky, beyond the atmosphere, its existence is well recorded.This is because Lygon often appears to others. In particular, it always appears on set dates during the year, at times when specific stars are visible together in the sky. Those times are well known to people. Lygon appears in a different location each time, but the locations where it might appear are always five specific areas. Great festivals are held there on the days where Lygon might appear. ",rbtn:"POISON",rbg:"#8b44c9",rank:"04", isSale:true,main: false},
    {bg:"linear-gradient(to right, #ffe000, #799f0c)",img:Polycat3,name:"Catty",desc:"An uncommon Polymon in the Polyverse.", details:"",rbtn:"GROUND",rbg:"#91705f",rank:"05", isSale:false,main: false},
    {bg:"linear-gradient(to right, #004ff9, #fff94c)",img:Polycat2,name:"Carp",desc:"A common Polymon in the Polyverse.", details:"",rbtn:"WATER",rbg:"#0034af",rank:"06", isSale:true,main: false},
    {bg:"linear-gradient(to right, #add100, #7b920a)",img:Polycat1,name:"Purr",desc:"A common Polymon in the Polyverse.", details:"",rbtn:"GROUND",rbg:"#91705f",rank:"07", isSale:false,main: false},
    {bg:"linear-gradient(to right, #03001e, #7303c0, #ec38bc, #fdeff9)",img:ANCE,name:"Ance",desc:"Ance created by BSC. A man bred PolyMon.", details:"Ance is the legendary lightning bird Polymon. It is also one of the few legendary Polymon – and Polymon in general – that does not have a nest of its own, or even a general area where it lives.Instead of having a permanent place, Ance simply follows storms. It as a supernatural instinct that allows it to know where in the world thunderstorms are currently ongoing, and exactly what direction they are heading. Ance is always traveling to the nearest thunderstorm. Once inside it, it flies among the clouds, absorbing the electrical energy of the storm and replenishing its powers.",rank:"08",main: false},
    // {img:ancee,name:"Ance",desc:"Ance created by BSC. A man bred PolyMon.", details:"Ance is the legendary lightning bird Polymon. It is also one of the few legendary Polymon – and Polymon in general – that does not have a nest of its own, or even a general area where it lives.Instead of having a permanent place, Ance simply follows storms. It as a supernatural instinct that allows it to know where in the world thunderstorms are currently ongoing, and exactly what direction they are heading. Ance is always traveling to the nearest thunderstorm. Once inside it, it flies among the clouds, absorbing the electrical energy of the storm and replenishing its powers.",rank:"08",main: true},
    // {img:biticc,name:"Bitic",desc:"Coming from the Lightning network. Legendary type of PolyMon.", details:"Bitic, the thunder dragon Polymon, holds domain over a large area of land. The land is mostly mountainous, and few other Polymon and humans live there. This is just as Bitic wants, as it prefers its own solitude. Bitic gathers enormous amounts of energy inside it simply by existing. Often, this energy needs to be released. Bitic releases it by creating large thunder and lightning explosions with it at the center. Those explosions do not harm Bitic, but make craters out of the nearby land. This is why Bitic prefers solitude, as anything near the explosion faces an early death.", rank:"01", isSale:true,main: true},
    // {img:ethee,name:"Ethe",desc:"Defender of Ether. Legendary type of PolyMon.", details:"Ethe, the legendary star steel dragon Polymon, is always roaming the world looking for powerful adversaries. Like Lygon, Ethe lives high up in the sky, beyond the atmosphere. Also like Lygon, it often comes descends. However, where Lygon comes down into the world to give gifts on specific days, Ethe only appears to affirm its supremacy. From high up beyond the atmosphere, Ethe is still able to see what is going on in the world. The moment it sees another Polymon boast of its strength, Ethe descends and challenges the other Polymon to a fight.",rbtn:"DARK",rbg:"#333",rank:"02", isSale:false,main: true},
    // {img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfMzs85aZz7350yudSJuHhJwSx-7kVWd5eEw&usqp=CAU",name:"nft9",desc:"a book or other written or printed work, "},
    // {img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfMzs85aZz7350yudSJuHhJwSx-7kVWd5eEw&usqp=CAU",name:"nft10",desc:"a book or other written or printed work, "},
    // {img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfMzs85aZz7350yudSJuHhJwSx-7kVWd5eEw&usqp=CAU",name:"nft11",desc:"a book or other written or printed work,"},
    // {img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfMzs85aZz7350yudSJuHhJwSx-7kVWd5eEw&usqp=CAU",name:"nft12",desc:"a book or other written or printed work, "},

]